#!/bin/sh

if [ -z $1 ] ; then
    echo "usage: $0 <desired-count>"
    exit
fi

DESIRED_CONNECTIONS_COUNT=$(($1-1))

cat /etc/opt/hosts > /tmp/active_connections
CURRENT_CONNECTIONS_COUNT=$(wc -l /tmp/active_connections)

while [ "$CURRENT_CONNECTIONS_COUNT" -lt "$DESIRED_CONNECTIONS_COUNT" ]; then
    sleep 1
    cat /etc/opt/hosts > /tmp/active_connections
    CURRENT_CONNECTIONS_COUNT=$(wc -l /tmp/active_connections)
done